[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=45"]

[project]
name = "circuitsvis"
description = "Mechanistic Interpretability Visualizations using React"
version="1.0.3"
license = { file = "LICENSE" }
dependencies = [
    "numpy",
]

[project.optional-dependencies]
dev = [
    "ipython", 
    "jupyterlab", 
    "mypy", 
    "pytest", 
    "snapshottest", 
    "twine"
]

